spring:
  port: 8180
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/default?createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect